# pubspec.yaml
# This file defines the project's dependencies, platform versions, and other metadata.
name: flutter_desktop_app
description: A simple Flutter desktop application with forms and Isar database.
publish_to: 'none' # Remove this line if you intend to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Navigation
  go_router: ^14.0.0 # For declarative routing.

  # State Management
  provider: ^6.1.2 # A simple yet powerful state management solution.

  # Database
  isar: ^3.1.0+1 # Updated to a stable version
  isar_flutter_libs: ^3.1.0+1 # Updated to a stable version
  path_provider: ^2.1.3

  # PDF Generation and Printing
  pdf: ^3.10.8
  printing: ^5.14.2
  # Date formatting
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

  # Isar code generation
  isar_generator: ^3.1.0 # Updated to a stable version
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  assets:
      - assets/images/


# To generate Isar files, run the following command in your terminal:
# flutter pub run build_runner build --delete-conflicting-outputs
